language: python
# Use new container-based Travis infrastructure.
sudo: false
# Cache pip packages. `cache: pip` does not work with custom install steps.
cache:
  directories:
    - $HOME/.cache/pip

os:
  - linux

python:
  - "2.7"


install:
  # Install wheel, upgrade pip to use wheel-cache
  - pip install -U pip wheel
  
  # Download-progress bars break Travis's log view. Disable them by piping output
  # through another program (if output is not a tty, no progress bars)
  # Install dependencies.
  - pip install -r requirements-mceditlib.txt | cat

  # Install dependencies for tests.
  - pip install -r tests/requirements.txt | cat

  # Install mceditlib.
  - python setup_mceditlib.py develop

script:
  - py.test -n 5 tests

